# Import Dependencies

In [47]:
import pandas as pd
import numpy as np

# Parse First Text File

In [49]:
file_path = 'llama_QA_questions.txt'
data = []

with open(file_path, 'r') as file:
    text = file.read()
    sections = text.split("Topic: ")
    #sections = text.split("### Response:")
    del sections[0]  # Remove the initial part before the question
    total_questions = len(sections)
    for section in sections:
        try:
            topic = section.split("### Response:")[0].strip()
            section = section.split("### Response:")[1].strip()
            question = section.split("Question:")[1].strip()
            question = question.split("Solution:")[0].strip()
            solution = section.split("Solution:")[1].strip()
            if "##" in question:
                question = question.split("##")[0]
            if "\n\n" in question:
                question = question.split("\n\n")
                question = "\n".join(question)
            if "\nBel" in solution:
                solution = solution.split("\nBel")[0]
            if "##" in solution:
                solution = solution.split("##")[0]
            if "return" not in solution:
                try: 
                    solution = solution + '\n' + '    return result'
                    solution_text = solution
                    try:
                            # Execute the Python code
                        exec(solution)
                        answer = solution()
                        if answer==None:
                            continue
                        data.append({"question": question, "solution": solution_text, 'answer': answer, 'topic': topic})
                    except: 
                        try: #pick up questions that did not indent the code block
                            solution_new = ""
                            lines = solution.split('\n')
                            indent = False
                            for line in lines:
                                if line.startswith('def solution():'):
                                    solution_new += line + '\n'

                                if not line.startswith('def solution():') and not line.startswith('    return result'):
                                    solution_new += '    ' + line + '\n'

                                if line.startswith('    return result'):
                                    solution_new += line
                            solution_text = solution_new
                            # Execute the Python code
                            exec(solution_new)
                            answer = solution()
                            if answer==None:
                                continue
                            data.append({"question": question, "solution": solution_text, 'answer': answer, "topic": topic})
                        except:
                                pass
                except:
                    pass
            if "return" in solution:
                try: 
                    solution_text = solution
                    try:
                        # Execute the Python code
                        exec(solution)
                        answer = solution()
                        if answer==None:
                            continue
                        data.append({"question": question, "solution": solution_text, 'answer': answer, "topic": topic})
                    except: 
                        try: #pick up questions that did not indent the code block
                            solution_new = ""
                            lines = solution.split('\n')
                            indent = False
                            for line in lines:
                                if line.startswith('def solution():'):
                                    solution_new += line + '\n'

                                if not line.startswith('def solution():') and not line.startswith('    return result'):
                                    solution_new += '    ' + line + '\n'

                                if line.startswith('    return result'):
                                    solution_new += line
                            solution_text = solution_new
                            # Execute the Python code
                            exec(solution_new)
                            answer = solution()
                            if answer==None:
                                continue
                            data.append({"question": question, "solution": solution_text, 'answer': answer, "topic": topic})
                        except:
                            pass
                except:
                    pass
        except:
            pass
df1 = pd.DataFrame.from_dict(data)
result1 = "Percentage of Questions with Executable Code: " + str((len(df1)/total_questions)*100)
result1

18

'Percentage of Questions with Executable Code: 62.52894858730894'

In [50]:
#this needs to be rewritten
def check_topic(df):
    count = 0
    for i in range(0, len(df)):
        if df.iloc[i]['topic'] in df.iloc[i]['question']:
            count+=1
            
    return "Percentage of Executable Code that Contains Topic: " + str((count/len(df))*100)
        
    
result2 = check_topic(df1)
result2

'Percentage of Executable Code that Contains Topic: 82.0'

In [51]:
df1

,question,solution,answer,topic
0,"In 2017, Captain America was 100 years old. 20...",def solution():\n #Captain America was 100 ...,33,Captain America
1,The volleyball team has 12 members. 5 of the m...,def solution():\n #The volleyball team has ...,0,volleyball
2,3 of the Ninja Turtles ate 12 pizzas. 2 ate 14...,def solution():\n #3 turtles ate 12 pizzas\...,82,Ninja Turtles
3,"T'Challa, the Black Panther, has 100 vibranium...",def solution():\n #T'Challa started with 10...,55,Black Panther
4,The New England Patriots and the Green Bay Pac...,def solution():\n #The Packers are 2/3 of t...,6,football
...,...,...,...,...
1345,Superman can leap 1000 feet in a single bound....,def solution():\n #Superman can leap 1000 f...,18000.0,Superman
1346,"Wakanda, the home of the Black Panther, is a s...",def solution():\n #Total Wakandan soldiers\...,1000.0,Black Panther
1347,Batman has 112 batarangs. He uses 11 batarangs...,def solution():\n #Batman started with 112 ...,83,Batman
1348,The Toronto Raptors have 2000 points. The Bost...,def solution():\n #The Raptors have 2000 po...,3200,basketball
1349,"Spiderman, the web-slinging superhero, is chas...",def solution():\n #Spiderman started with 2...,16,Spiderman

# Parse Second Text File

In [52]:
file_path = 'llama_QA_questions_v2.txt'
data = []

with open(file_path, 'r') as file:
    text = file.read()
    sections = text.split("Topic: ")
    #sections = text.split("### Response:")
    del sections[0]  # Remove the initial part before the question
    total_questions = len(sections)
    for section in sections:
        try:
            topic = section.split("### Response:")[0].strip()
            section = section.split("### Response:")[1].strip()
            question = section.split("Question:")[1].strip()
            question = question.split("Solution:")[0].strip()
            solution = section.split("Solution:")[1].strip()
            if "##" in question:
                question = question.split("##")[0]
            if "\n\n" in question:
                question = question.split("\n\n")
                question = "\n".join(question)
            if "\nBel" in solution:
                solution = solution.split("\nBel")[0]
            if "##" in solution:
                solution = solution.split("##")[0]
            if "return" not in solution:
                try: 
                    solution = solution + '\n' + '    return result'
                    solution_text = solution
                    try:
                            # Execute the Python code
                        exec(solution)
                        answer = solution()
                        if answer==None:
                            continue
                        data.append({"question": question, "solution": solution_text, 'answer': answer, 'topic': topic})
                    except: 
                        try: #pick up questions that did not indent the code block
                            solution_new = ""
                            lines = solution.split('\n')
                            indent = False
                            for line in lines:
                                if line.startswith('def solution():'):
                                    solution_new += line + '\n'

                                if not line.startswith('def solution():') and not line.startswith('    return result'):
                                    solution_new += '    ' + line + '\n'

                                if line.startswith('    return result'):
                                    solution_new += line
                            solution_text = solution_new
                            # Execute the Python code
                            exec(solution_new)
                            answer = solution()
                            if answer==None:
                                continue
                            data.append({"question": question, "solution": solution_text, 'answer': answer, "topic": topic})
                        except:
                                pass
                except:
                    pass
            if "return" in solution:
                try: 
                    solution_text = solution
                    try:
                        # Execute the Python code
                        exec(solution)
                        answer = solution()
                        if answer==None:
                            continue
                        data.append({"question": question, "solution": solution_text, 'answer': answer, "topic": topic})
                    except: 
                        try: #pick up questions that did not indent the code block
                            solution_new = ""
                            lines = solution.split('\n')
                            indent = False
                            for line in lines:
                                if line.startswith('def solution():'):
                                    solution_new += line + '\n'

                                if not line.startswith('def solution():') and not line.startswith('    return result'):
                                    solution_new += '    ' + line + '\n'

                                if line.startswith('    return result'):
                                    solution_new += line
                            solution_text = solution_new
                            # Execute the Python code
                            exec(solution_new)
                            answer = solution()
                            if answer==None:
                                continue
                            data.append({"question": question, "solution": solution_text, 'answer': answer, "topic": topic})
                        except:
                            pass
                except:
                    pass
        except:
            pass
df2 = pd.DataFrame.from_dict(data)
result1 = "Percentage of Questions with Executable Code: " + str((len(df2)/total_questions)*100)
result1

'Percentage of Questions with Executable Code: 63.665447897623395'

In [53]:
result2 = check_topic(df2)
result2

'Percentage of Executable Code that Contains Topic: 82.19669777458722'

In [54]:
df2

,question,solution,answer,topic
0,Spiderman has 12 web-shooters. He uses 3 of th...,def solution():\n #Spiderman started with 1...,0,Spiderman
1,Taylor Swift is in the process of recording a ...,def solution():\n #Taylor Swift started wit...,26,Taylor Swift
2,Captain America is in a rush to save the world...,def solution():\n #The first checkpoint is ...,5250.0,Captain America
3,There are 4 Ninja Turtles. 2 of them are 150 y...,def solution():\n #The ages of the Ninja Tu...,146.25,Ninja Turtles
4,"500 cars, 200 of which are convertibles, are l...",def solution():\n #There are 500 cars\n ...,430.0,cars
...,...,...,...,...
1388,120 cars are in a parking lot. 40 more cars en...,def solution():\n #There were 120 cars in t...,136.0,cars
1389,2009 was a good year for the Tesla car company...,def solution():\n #Tesla sold 2500 cars in ...,5500,cars
1390,The Charmander family of Pokémon has 3 evoluti...,def solution():\n #A Charmander is 2.5 feet...,9.375,Pokémon
1391,"In the Mushroom Kingdom, there are 5000 toads....",def solution():\n #Total toads in Mushroom ...,1500,Super Mario
1392,The 4:00 PM train from Penn Station to New Hav...,def solution():\n #Train from Penn Station ...,3.5,trains

# Parse General Questions

In [55]:
file_path = 'llama_QA_questions_general.txt'
data = []

with open(file_path, 'r') as file:
    text = file.read()
    #sections = text.split("Topic: ")
    sections = text.split("### Response:")
    del sections[0]  # Remove the initial part before the question
    total_questions = len(sections)
    for section in sections:
        try:
            question = section.split("Question:")[1].strip()
            question = question.split("Solution:")[0].strip()
            solution = section.split("Solution:")[1].strip()
            if "##" in question:
                question = question.split("##")[0]
            if "\n\n" in question:
                question = question.split("\n\n")
                question = "\n".join(question)
            if "\nBel" in solution:
                solution = solution.split("\nBel")[0]
            if "##" in solution:
                solution = solution.split("##")[0]
            if "return" not in solution:
                try: 
                    solution = solution + '\n' + '    return result'
                    solution_text = solution
                    try:
                            # Execute the Python code
                        exec(solution)
                        answer = solution()
                        if answer==None:
                            continue
                        data.append({"question": question, "solution": solution_text, 'answer': answer, 'topic': ""})
                    except: 
                        try: #pick up questions that did not indent the code block
                            solution_new = ""
                            lines = solution.split('\n')
                            indent = False
                            for line in lines:
                                if line.startswith('def solution():'):
                                    solution_new += line + '\n'

                                if not line.startswith('def solution():') and not line.startswith('    return result'):
                                    solution_new += '    ' + line + '\n'

                                if line.startswith('    return result'):
                                    solution_new += line
                            solution_text = solution_new
                            # Execute the Python code
                            exec(solution_new)
                            answer = solution()
                            if answer==None:
                                continue
                            data.append({"question": question, "solution": solution_text, 'answer': answer, "topic": ""})
                        except:
                                pass
                except:
                    pass
            if "return" in solution:
                try: 
                    solution_text = solution
                    try:
                        # Execute the Python code
                        exec(solution)
                        answer = solution()
                        if answer==None:
                            continue
                        data.append({"question": question, "solution": solution_text, 'answer': answer, "topic": ""})
                    except: 
                        try: #pick up questions that did not indent the code block
                            solution_new = ""
                            lines = solution.split('\n')
                            indent = False
                            for line in lines:
                                if line.startswith('def solution():'):
                                    solution_new += line + '\n'

                                if not line.startswith('def solution():') and not line.startswith('    return result'):
                                    solution_new += '    ' + line + '\n'

                                if line.startswith('    return result'):
                                    solution_new += line
                            solution_text = solution_new
                            # Execute the Python code
                            exec(solution_new)
                            answer = solution()
                            if answer==None:
                                continue
                            data.append({"question": question, "solution": solution_text, 'answer': answer, "topic": ""})
                        except:
                            pass
                except:
                    pass
        except:
            pass
df3 = pd.DataFrame.from_dict(data)
result1 = "Percentage of Questions with Executable Code: " + str((len(df3)/total_questions)*100)
result1

387420489

'Percentage of Questions with Executable Code: 32.276938078985864'

In [56]:
df3

,question,solution,answer,topic
0,The bakers at the Beverly Hills Bakery baked 2...,def solution():\n #The bakers started with ...,74,
1,The bakers at the Beverly Hills Bakery baked 2...,def solution():\n #The bakers started with ...,74,
2,A candy store sells 1000 lollipops a day. 200 ...,def solution():\n #The candy store sells 10...,100,
3,A pig farmer has 500 pigs. 100 of the pigs are...,def solution():\n #There are 500 pigs\n ...,417.5,
4,The number of toys in a toy box is 20. 1/4 of ...,def solution():\n #The number of toys in a ...,5.0,
...,...,...,...,...
657,1240 toothpicks were used to make 500 aestheti...,def solution():\n #1240 toothpicks were use...,-58760,
658,"A bakery sells 12 baguettes, 30 croissants, an...","def solution():\n #baguettes, croissants, a...",2,
659,A 25-gallon aquarium and a 50-gallon aquarium ...,def solution():\n #25-gallon aquarium is 10...,2.5,
660,The 12-year-old is 48 inches tall. The 14-year...,def solution():\n #The 12-year-old is 48 in...,24,
661,The 23-pound turkey was 120 degrees when it wa...,def solution():\n #Initial temperature of t...,-280.0,

# Concat DFs

In [59]:
df = pd.concat([df1, df2, df3])
df = df.drop_duplicates(subset='question')
df = df.sample(frac = 1)
question_numbers = []
for i in range(0, len(df)):
    question_numbers.append(f"question_{i}")
df['question_number'] = question_numbers
df.to_csv("data\llama_QA_questions.csv")

In [60]:
len(df)
df

,question,solution,answer,topic,question_number
1300,Taylor Swift has 1000s of fans.\n200 of them a...,def solution():\n\n # total number of fans\n ...,0,Taylor Swift,question_0
632,1000000000000 (one trillion) is the 12th numbe...,def solution():\n #The 12th number in the s...,1000000000000000000000000000,,question_1
591,The 12:10 to 5:10 train is 30 minutes late. Th...,def solution():\n #The 12:10 to 5:10 train ...,60,trains,question_2
1014,If 32500000 cookies are divided equally among ...,def solution():\n #32500000 cookies are to ...,6.5,cookies,question_3
601,The 12:05 train from Penn Station to Union Sta...,def solution():\n #The 12:05 train is 50 mi...,-65,trains,question_4
...,...,...,...,...,...
961,The Cincinnati Bengals have 45 players on thei...,def solution():\n #Total number of players\...,30,football,question_3231
33,Hello Kitty's piggy bank has 40 coins. She als...,def solution():\n #Hello Kitty has 40 coins...,42.0,Hello Kitty,question_3232
95,Superman can leap 1200 feet in a single bound....,def solution():\n # Superman is on the 1000...,0.833333,Superman,question_3233
64,Thor is a 12-pound dog. He is 20 inches from ...,def solution():\n #Thor's initial weight\n ...,"(14.399999999999999, 30.0)",Thor,question_3234
522,"Thor, the God of Thunder, has 12000 lightning ...",def solution():\n #Thor started with 12000 ...,6000.0,Thor,question_3235

In [25]:
df_temp = df[df['question'].str.contains('Superman')]
df_temp.iloc[-1]['question']

'Superman can fly 1200 miles per hour. He can also run 500 miles per hour. If he flies for 2 hours and runs for 3 hours, how many miles has he covered?'

# Send Each Question to .txt file for Zooniverse Upload

In [14]:
for i in range(0, len(df)):
    question_number = df.iloc[i]['question_number']
    question = df.iloc[i]['question']
    solution = df.iloc[i]['solution']
    answer = str(df.iloc[i]['answer'])
    file_name = f"{question_number}.txt"
    file_path = "Zooniverse/"+file_name
    text = "Question Number: " + question_number + "\n\nQuestion:\n" + question + "\n\nSolution:\n" + solution + "\n\nAnswer: " + answer
    with open(file_path, "w") as f:  # Open the file in append mode ("a")
        f.write(text)  # Append the newly generated text to the file