In [1]:
import pandas as pd
sgsm = pd.read_csv('data/sgsm_train.csv')

In [2]:
sgsm

,Unnamed: 0,question,solution,answer,topic
0,0,"LeBron James is 6'9"" tall. 1 inch is 2.54 cm. ...","def solution():\n #LeBron James is 6'9"" tal...",205.74,basketball
1,1,Captain America has 1200 ryo. He spends 400 ry...,def solution():\n #Captain America started ...,300.0,Captain America
2,3,3 scoops of ice cream cost $4. \nHow much does...,def solution():\n #3 scoops of ice cream co...,13.333333333333332,ice cream
3,5,A volleyball team is 6 players. \n3 of the pla...,def solution():\n #3 of the players are 16 ...,16.666666666666668,volleyball
4,6,"Superman can fly at a speed of 1,000 miles per...",def solution():\n #Superman can fly at a sp...,0.2,Superman
...,...,...,...,...,...
2088,1901,30 unicorns are in a herd. 10 unicorns in the ...,def solution():\n #Total number of unicorns...,17,unicorns
2089,1902,A pizza has 8 slices. 4 of the slices have pep...,def solution():\n #A pizza has 8 slices\n ...,4,pizza
2090,1903,12000 people were at a rally. 10000 of them we...,def solution():\n #Total number of people a...,500,unspecified
2091,1904,A bakery made 300 muffins. 150 of the muffins ...,def solution():\n #Total muffins\n total...,60,unspecified
2092,1905,A pizza is cut into 12 slices. 5 slices are to...,def solution():\n #A pizza is cut into 12 s...,6,pizza

In [4]:
sgsm = sgsm[['question', 'answer']]

In [13]:
for i in range(0, len(sgsm)):
    try:
        answer = sgsm.iloc[i]['answer']
        answer = float(answer)
        answer = str(answer)
        sgsm.iloc[i]['answer'] = answer
    except:
        sgsm = sgsm.drop([i])

/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer
/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer
/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer
/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer
/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer
/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer
/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer
/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer
/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer
/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer
/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer
/var/folders/ms/lv6zlm_16wx8dzf7c_t51b0r0000gn/T/ipykernel_5900/4199284318.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sgsm.iloc[i]['answer'] = answer

In [14]:
sgsm

                                               question              answer
0     LeBron James is 6'9" tall. 1 inch is 2.54 cm. ...              205.74
1     Captain America has 1200 ryo. He spends 400 ry...               300.0
2     3 scoops of ice cream cost $4. \nHow much does...  13.333333333333332
3     A volleyball team is 6 players. \n3 of the pla...  16.666666666666668
4     Superman can fly at a speed of 1,000 miles per...                 0.2
...                                                 ...                 ...
2076  A herd of unicorns has 100 unicorns. 25 of the...                64.0
2077  525 students are in the 11th grade. 110 of the...               270.0
2078  1000 students are at a candy tasting. 100 of t...               750.0
2079  2300 people are at a rally. 500 of them are we...               900.0
2080  4000 people were at a rally. 2000 of them were...              1300.0

[2047 rows x 2 columns]

In [15]:
sgsm.to_csv('data/sgsm_train_eval.csv', index=False)