In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Data/mathwell-mathematics-assessment-through-word-problems-extracted-from-large-language-models-classifications.csv')
df

,classification_id,user_name,user_id,user_ip,workflow_id,workflow_name,workflow_version,created_at,gold_standard,expert,metadata,annotations,subject_data,subject_ids
0,501808106,bryanchrist,2631956.0,7d37e0b307466efd32e9,24740,Classify Questions,37.630,2023-07-18 16:13:14 UTC,NaN,NaN,"{""source"":""api"",""session"":""9a2534a2cdf37064e69...","[{""task"":""T0"",""task_label"":""Is this question s...","{""90771026"":{""retired"":null,""Filename"":""questi...",90771026
1,501808147,bryanchrist,2631956.0,7d37e0b307466efd32e9,24740,Classify Questions,37.630,2023-07-18 16:13:27 UTC,NaN,NaN,"{""source"":""api"",""session"":""9a2534a2cdf37064e69...","[{""task"":""T0"",""task_label"":""Is this question s...","{""90771026"":{""retired"":null,""Filename"":""questi...",90771026
2,501808176,bryanchrist,2631956.0,7d37e0b307466efd32e9,24740,Classify Questions,37.630,2023-07-18 16:13:36 UTC,NaN,NaN,"{""source"":""api"",""session"":""9a2534a2cdf37064e69...","[{""task"":""T0"",""task_label"":""Is this question s...","{""90771026"":{""retired"":null,""Filename"":""questi...",90771026
3,501808272,bryanchrist,2631956.0,7d37e0b307466efd32e9,24740,Classify Questions,37.630,2023-07-18 16:14:12 UTC,NaN,NaN,"{""source"":""api"",""session"":""9a2534a2cdf37064e69...","[{""task"":""T0"",""task_label"":""Is this question s...","{""90771026"":{""retired"":null,""Filename"":""questi...",90771026
4,501809115,bryanchrist,2631956.0,7d37e0b307466efd32e9,24740,Classify Questions,37.630,2023-07-18 16:19:32 UTC,NaN,NaN,"{""source"":""api"",""session"":""9a2534a2cdf37064e69...","[{""task"":""T0"",""task_label"":""Is this question s...","{""90771026"":{""retired"":null,""Filename"":""questi...",90771026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3346,522083991,kidleader,2668795.0,08eabcdf650dd5c4e6d9,24740,Classify Questions,114.169,2023-11-13 11:33:12 UTC,NaN,NaN,"{""source"":""api"",""session"":""6bb24cc168de19fb568...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92650989"":{""retired"":null,""Filename"":""questi...",92650989
3347,522084080,kidleader,2668795.0,08eabcdf650dd5c4e6d9,24740,Classify Questions,114.169,2023-11-13 11:33:56 UTC,NaN,NaN,"{""source"":""api"",""session"":""6bb24cc168de19fb568...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92653505"":{""retired"":{""id"":121034266,""workfl...",92653505
3348,522084167,kidleader,2668795.0,08eabcdf650dd5c4e6d9,24740,Classify Questions,114.169,2023-11-13 11:34:38 UTC,NaN,NaN,"{""source"":""api"",""session"":""6bb24cc168de19fb568...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92653826"":{""retired"":null,""Filename"":""questi...",92653826
3349,522084245,kidleader,2668795.0,262c84f419c3f8606fd9,24740,Classify Questions,114.169,2023-11-13 11:35:07 UTC,NaN,NaN,"{""source"":""api"",""session"":""6bb24cc168de19fb568...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92653254"":{""retired"":null,""Filename"":""questi...",92653254
3350,522084339,kidleader,2668795.0,262c84f419c3f8606fd9,24740,Classify Questions,114.169,2023-11-13 11:35:38 UTC,NaN,NaN,"{""source"":""api"",""session"":""6bb24cc168de19fb568...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92650487"":{""retired"":null,""Filename"":""questi...",92650487

In [3]:
start_index = 166
df = df[start_index:]
df

,classification_id,user_name,user_id,user_ip,workflow_id,workflow_name,workflow_version,created_at,gold_standard,expert,metadata,annotations,subject_data,subject_ids
166,518580047,bryanchrist,2631956.0,b92f1a6132ce5d18f0a7,24740,Classify Questions,114.169,2023-10-26 15:44:26 UTC,NaN,NaN,"{""source"":""api"",""session"":""0588d55084272e4128a...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92652275"":{""retired"":null,""Filename"":""questi...",92652275
167,518580331,bryanchrist,2631956.0,b92f1a6132ce5d18f0a7,24740,Classify Questions,114.169,2023-10-26 15:45:16 UTC,NaN,NaN,"{""source"":""api"",""session"":""0588d55084272e4128a...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92650744"":{""retired"":null,""Filename"":""questi...",92650744
168,518580963,bryanchrist,2631956.0,8f5a66f9f8b2103ad0ac,24740,Classify Questions,114.169,2023-10-26 15:46:58 UTC,NaN,NaN,"{""source"":""api"",""session"":""0588d55084272e4128a...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92651965"":{""retired"":null,""Filename"":""questi...",92651965
169,518581032,bryanchrist,2631956.0,8f5a66f9f8b2103ad0ac,24740,Classify Questions,114.169,2023-10-26 15:47:10 UTC,NaN,NaN,"{""source"":""api"",""session"":""0588d55084272e4128a...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92654071"":{""retired"":null,""Filename"":""questi...",92654071
170,518581136,bryanchrist,2631956.0,8f5a66f9f8b2103ad0ac,24740,Classify Questions,114.169,2023-10-26 15:47:26 UTC,NaN,NaN,"{""source"":""api"",""session"":""0588d55084272e4128a...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92650910"":{""retired"":null,""Filename"":""questi...",92650910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3346,522083991,kidleader,2668795.0,08eabcdf650dd5c4e6d9,24740,Classify Questions,114.169,2023-11-13 11:33:12 UTC,NaN,NaN,"{""source"":""api"",""session"":""6bb24cc168de19fb568...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92650989"":{""retired"":null,""Filename"":""questi...",92650989
3347,522084080,kidleader,2668795.0,08eabcdf650dd5c4e6d9,24740,Classify Questions,114.169,2023-11-13 11:33:56 UTC,NaN,NaN,"{""source"":""api"",""session"":""6bb24cc168de19fb568...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92653505"":{""retired"":{""id"":121034266,""workfl...",92653505
3348,522084167,kidleader,2668795.0,08eabcdf650dd5c4e6d9,24740,Classify Questions,114.169,2023-11-13 11:34:38 UTC,NaN,NaN,"{""source"":""api"",""session"":""6bb24cc168de19fb568...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92653826"":{""retired"":null,""Filename"":""questi...",92653826
3349,522084245,kidleader,2668795.0,262c84f419c3f8606fd9,24740,Classify Questions,114.169,2023-11-13 11:35:07 UTC,NaN,NaN,"{""source"":""api"",""session"":""6bb24cc168de19fb568...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92653254"":{""retired"":null,""Filename"":""questi...",92653254
3350,522084339,kidleader,2668795.0,262c84f419c3f8606fd9,24740,Classify Questions,114.169,2023-11-13 11:35:38 UTC,NaN,NaN,"{""source"":""api"",""session"":""6bb24cc168de19fb568...","[{""task"":""T0"",""task_label"":""Is this question s...","{""92650487"":{""retired"":null,""Filename"":""questi...",92650487

In [4]:
import json
solvability = []
accuracy = []
appropriateness = []
notes = []
for i in range(0, len(df)):
    my_json = json.loads(df.iloc[i]['annotations'])
    solvability.append(my_json[0]['value'])
    if my_json[1]['task']=='T4':
        accuracy.append(my_json[1]['value'])
    if my_json[1]['task']!='T4':
        accuracy.append("NA")
        appropriateness.append(my_json[1]['value'])
    if my_json[2]['task']=='T1':
        appropriateness.append(my_json[2]['value'])
    if my_json[2]['task']!='T1':
        notes.append(my_json[2]['value'])
    try:
        notes.append(my_json[3]['value'])
    except:
        pass
df['solvability']=solvability
df['appropriateness']=appropriateness
df['accuracy']=accuracy
df['notes']=notes

<ipython-input-4-b75638aa5026>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['solvability']=solvability
<ipython-input-4-b75638aa5026>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['appropriateness']=appropriateness
<ipython-input-4-b75638aa5026>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['accuracy']=accuracy
<ipython-input-4-b75638aa5026>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['notes']=notes

In [5]:
question_numbers = []
for i in range(0, len(df)):
    my_json = json.loads(df.iloc[i]['subject_data'])
    subject_id = df.iloc[i]['subject_ids']
    question_number = my_json[f'{subject_id}']['Filename']
    question_number = question_number.split(".txt")[0]
    question_numbers.append(question_number)
df['question_number']=question_numbers

<ipython-input-5-6fbe7029c2dd>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['question_number']=question_numbers

In [6]:
import numpy as np
replace_map = {"Yes": 1, "No": 0, "NA": np.nan}
df['solvability'] = df['solvability'].replace(replace_map)
df['accuracy'] = df['accuracy'].replace(replace_map)
replace_map = {"Yes: This question is understandable, appropriate and a middle school student or younger could solve it ": 1, 
               "No: This question is strange, confusing, contains conflicting information, and/or is not based in reality": 0, 
               "No: This question contains distracting typos or grammatical errors": 0, 
               "No: This question contains inappropriate material": 0, 
              "No: The question is too hard, even for a middle school student": 0}
df['appropriateness'] = df['appropriateness'].replace(replace_map)

<ipython-input-6-eedc2057c577>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['solvability'] = df['solvability'].replace(replace_map)
<ipython-input-6-eedc2057c577>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['accuracy'] = df['accuracy'].replace(replace_map)
<ipython-input-6-eedc2057c577>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['appropriateness'] = df['appropriateness'].replace(replace_map)

In [9]:
df = df[['user_name','question_number', 'solvability', 'accuracy', 'appropriateness', 'notes']]
df = df[df['user_name']=='bryanchrist']
df = df[['question_number', 'accuracy', 'solvability', 'appropriateness']]

In [10]:
questions = pd.read_csv('llama_QA_questions.csv')
questions

,Unnamed: 0,question,solution,answer,topic,question_number
0,584,4 unicorns ate 24 apples. 3 of the unicorns at...,def solution():\n #4 unicorns ate 24 apples...,0,unicorns,question_0
1,562,240 scoops of ice cream were evenly divided in...,def solution():\n #Total scoops of ice crea...,8.0,ice cream,question_1
2,1107,T'Challa is the king of Wakanda. He has 2000 w...,def solution():\n #T'Challa has 2000 warrio...,1500,Black Panther,question_2
3,199,24 cars were in a parking lot. 14 more cars ca...,def solution():\n #There were 24 cars in th...,31,cars,question_3
4,1080,A lacrosse team has 24 players. 11 of the play...,def solution():\n #Total players\n total...,0,lacrosse,question_4
...,...,...,...,...,...,...
3231,692,"Barbie has 245 1s, 225 5s, 123 10s, and 124 20...",def solution():\n #Barbie has 245 1s\n o...,5080,Barbie,question_3231
3232,862,"Thor, the God of Thunder, is 2000 years old. 1...",def solution():\n #Thor is 2000 years old\n...,2250,Thor,question_3232
3233,283,"Wonder Woman is 6,000 years old. 5,000 years a...","def solution():\n #Wonder Woman is 6,000 ye...",1100,Wonder Woman,question_3233
3234,237,The mall has 521 parking spots. 128 of the par...,def solution():\n #Total parking spots\n ...,100,NaN,question_3234
3235,133,3000 cookies are baked in an oven. 2/5 of the ...,def solution():\n #3000 cookies are baked\n...,3000,cookies,question_3235

In [11]:
merged = pd.merge(df, questions,
              on = 'question_number',
              how='inner')
merged

,question_number,accuracy,solvability,appropriateness,Unnamed: 0,question,solution,answer,topic
0,question_1521,1.0,1,1,633,A candy store has 45000 pieces of candy. 10000...,def solution():\n #The candy store has 4500...,15000,candy
1,question_279,0.0,1,0,403,The 12:05 p.m. train from New York to Boston i...,def solution():\n #The 12:05 p.m. train is ...,-0.08333333333333348,trains
2,question_1266,1.0,1,0,75,Taylor Swift is on a 2-year contract with her ...,def solution():\n #Taylor Swift has to prod...,1.4583333333333333,Taylor Swift
3,question_2923,1.0,1,1,568,The Beverly Hills Bakery baked 200 loaves of b...,def solution():\n #The bakers at the Beverl...,290,NaN
4,question_414,NaN,0,0,807,There are 4 Ninja Turtles. 3 of them are weari...,def solution():\n #There are 4 Ninja Turtle...,0,Ninja Turtles
...,...,...,...,...,...,...,...,...,...
2267,question_1416,1.0,1,1,623,"The Cincinnati Bengals have 375 rushing yards,...",def solution():\n #rushing yards\n rushi...,1315,football
2268,question_472,0.0,1,1,1242,There are 150 different kinds of PokÃ©mon. 50% ...,def solution():\n #There are 150 different ...,30.0,PokÃ©mon
2269,question_2082,1.0,1,1,1315,A bakery is baking 1000 cookies. 400 of the co...,def solution():\n #Total cookies\n total...,300,cookies
2270,question_986,0.0,1,1,512,A 25-meter pool is 2.5 times as long as a 10-m...,def solution():\n # The 25-meter pool is 2....,40.0,swimming
2271,question_2122,1.0,1,1,120,"Patrick Mahomes, the quarterback for the Kansa...",def solution():\n #Patrick Mahomes has 2000...,1800,Patrick Mahomes

In [12]:
merged['text'] = "Question: " + merged['question'] + "\nSolution:\n" + merged['solution'] + "\nAnswer: " + merged['answer']

In [13]:
appropriateness = merged[['appropriateness', 'text']]
appropriateness = appropriateness.rename({'appropriateness': 'label'}, axis = 1)
appropriateness.to_csv('data/appropriateness_test.csv')
appropriateness

      label                                               text
0         1  Question: A candy store has 45000 pieces of ca...
1         0  Question: The 12:05 p.m. train from New York t...
2         0  Question: Taylor Swift is on a 2-year contract...
3         1  Question: The Beverly Hills Bakery baked 200 l...
4         0  Question: There are 4 Ninja Turtles. 3 of them...
...     ...                                                ...
2267      1  Question: The Cincinnati Bengals have 375 rush...
2268      1  Question: There are 150 different kinds of Pok...
2269      1  Question: A bakery is baking 1000 cookies. 400...
2270      1  Question: A 25-meter pool is 2.5 times as long...
2271      1  Question: Patrick Mahomes, the quarterback for...

[2272 rows x 2 columns]

In [15]:
len(df[df['appropriateness']==0])

738